import React from 'react';
import Layout from '../components/Layout';

function PrivacyTerms() {
  return (
    <Layout>
      <div className="container">
        <h1>Privacy Policy for AsktheWitch.com</h1>
        <p>Last Updated: 18/04/2025</p>

        <h2>1. Introduction</h2>
        <p>This Privacy Policy describes how TBI Limited ("we," "us," or "our") collects, uses, and shares personal information of users ("you" or "users") of the AsktheWitch.com website (the "Website"). By using the Website, you consent to the practices described in this Privacy Policy.</p>

        <h2>2. Information We Collect</h2>
        <p>We may collect the following types of information from you:</p>
        <ul>
          <li><strong>Information You Provide Directly:</strong> This may include your email address if you contact us through the contact form, or any other information you voluntarily submit through the Website.</li>
          <li><strong>Automatically Collected Information:</strong> When you access and use our Website, we may automatically collect certain information about your device and usage, including:
            <ul>
              <li><strong>Log Data:</strong> Your IP address, browser type, operating system, referring URLs, pages visited, and the dates/times of your visits.</li>
              <li><strong>Cookies and Similar Technologies:</strong> We may use cookies and similar tracking technologies to collect information about your browsing activities. You can control cookies through your browser settings.</li>
            </ul>
          </li>
          <li><strong>AI-Generated Prompts and Responses:</strong> When you use the AI-powered features of the Website, the prompts you enter and the responses generated by the AI are recorded for the purpose of providing and improving the service. Please be mindful of the information you input into the AI.</li>
        </ul>

        <h2>3. How We Use Your Information</h2>
        <p>We may use the information we collect for the following purposes:</p>
        <ul>
          <li>To provide, operate, and maintain our Website.</li>
          <li>To respond to your inquiries and provide customer support.</li>
          <li>To analyze and improve the Website and its features, including the AI functionality.</li>
          <li>To monitor and analyze trends, usage, and activities in connection with our Website.</li>
          <li>To detect, prevent, and address technical issues and security incidents.</li>
          <li>To comply with applicable laws, regulations, and legal processes.</li>
        </ul>

        <h2>4. Sharing Your Information</h2>
        <p>We may share your information with third parties in the following circumstances:</p>
        <ul>
          <li><strong>Service Providers:</strong> We may engage third-party service providers to assist with website hosting, data analysis, email delivery, and other services. These providers will have access to your information only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</li>
          <li><strong>Legal Compliance:</strong> We may disclose your information if required to do so by law or in response to valid legal process (e.g., a subpoena or court order).</li>
          <li><strong>Business Transfers:</strong> In the event of a merger, acquisition, or sale of all or a portion of our assets, your information may be transferred as part of the transaction. We will notify you via email and/or a prominent notice on our Website of any change in ownership or uses of your personal information.</li>
          <li><strong>Aggregated and Anonymized Data:</strong> We may share aggregated and anonymized information that does not directly identify you with third parties for research, analytics, and other purposes.</li>
        </ul>

        <h2>5. Your Rights and Choices</h2>
        <p>Depending on your location, you may have certain rights regarding your personal information, including the right to:</p>
        <ul>
          <li>Access the personal information we hold about you.</li>
          <li>Request the correction of inaccurate or incomplete personal information.</li>
          <li>Request the deletion of your personal information.</li>
          <li>Object to the processing of your personal information.</li>
          <li>Request the restriction of the processing of your personal information.</li>
          <li>Receive your personal information in a portable format.</li>
          <li>Withdraw your consent at any time (where processing is based on consent).</li>
        </ul>
        <p>To exercise these rights, please contact us using the information provided in the "Contact Us" section.</p>

        <h2>6. Data Security</h2>
        <p>We take reasonable measures to protect your personal information from unauthorized access, use, or disclosure. However, no method of transmission over the internet or method of electronic storage is completely secure. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.</p>

        <h2>7. Data Retention</h2>
        <p>We will retain your personal information for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law.</p>

        <h2>8. Children's Privacy</h2>
        <p>Our Website is not intended for children under the age of 16. We do not knowingly collect personal information from children under this age. If we become aware that we have collected personal information from a child under the relevant age, we will take steps to delete such information as soon as possible.</p>

        <h2>9. International Data Transfers</h2>
        <p>Your personal information may be transferred to and maintained on computer systems located outside of your state, province, country, or other governmental jurisdiction where the privacy laws may not be as protective as those in your jurisdiction. By using the Website, you consent to such transfers.</p>

        <h2>10. Changes to This Privacy Policy</h2>
        <p>We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy on this page and updating the "Last Updated" date at the top. We encourage you to review this Privacy Policy periodically for any changes.</p>

        <h2>11. Contact Us</h2>
        <p>If you have any questions or concerns about this Privacy Policy or our data practices, please contact us through the contact form available on our Website.</p>
      </div>
    </Layout>
  );
}

export default PrivacyTerms;