import React from 'react';
import Layout from '../components/Layout';

function TermsOfService() { // Consider renaming this component to TermsOfService
  return (
    <Layout>
      <div className="container">
        <h1>Terms of Service for AsktheWitch.com</h1>
        <p>Last Updated: [18/04/2025]</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using AsktheWitch.com (the "Website"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Website.</p>

        <h2>2. Use of the Website</h2>
        <p>The Website provides AI-powered tools and information. You agree to use the Website for lawful purposes only and in a manner that does not infringe the rights of, restrict, or inhibit anyone else's use and enjoyment of the Website.</p>

        <h2>3. AI-Generated Content</h2>
        <p>The content generated by the AI on this Website is for informational and entertainment purposes only. It should not be considered professional advice. We do not guarantee the accuracy, completeness, or suitability of the AI-generated content for any specific purpose. You are solely responsible for your reliance on any AI-generated content.</p>

        <h2>4. User Input</h2>
        <p>You are responsible for the prompts and information you input into the AI. You agree not to submit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically, or otherwise objectionable.</p>

        <h2>5. Intellectual Property</h2>
        <p>The Website and its original content, features, and functionality (including but not limited to text, graphics, logos, and software) are owned by TBI Limited and are protected by copyright, trademark, and other intellectual property laws. You may not modify, reproduce, distribute, create derivative works of, publicly display, or in any way exploit any of the content on the Website without our prior written consent.</p>
        <p>You acknowledge and agree that the prompts you input into the AI are owned by you, and the AI-generated responses are owned by us. However, we grant you a non-exclusive, non-transferable, revocable license to use the AI-generated content for your personal, non-commercial use in connection with your use of the Website.</p>

        <h2>6. Disclaimer of Warranties</h2>
        <p>THE WEBSITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR COURSE OF PERFORMANCE. WE DO NOT WARRANT THAT THE WEBSITE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>

        <h2>7. Limitation of Liability</h2>
        <p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL TBI LIMITED BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR INABILITY TO ACCESS OR USE, THE WEBSITE.</p>

        <h2>8. Indemnification</h2>
        <p>You agree to indemnify, defend, and hold harmless TBI Limited and its affiliates, officers, directors, employees, agents, licensors, and suppliers from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your use of the Website or your breach of these Terms.</p>

        <h2>9. Governing Law</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of Panama, without regard to its conflict of law provisions.</p>

        <h2>10. Changes to These Terms</h2>
        <p>We may revise these Terms at any time without notice. By continuing to access or use the Website after those revisions become effective, you agree to be bound by the revised Terms. We encourage you to review these Terms periodically for any changes.</p>

        <h2>11. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us through the contact form available on our Website.</p>
      </div>
    </Layout>
  );
}

export default TermsOfService; // Or rename to TermsOfService if you create a separate file